<a href="https://colab.research.google.com/github/Yashb404/MUJ-ML-Lab/blob/main/ML_Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

url = "https://raw.githubusercontent.com/rashida048/Datasets/master/StudentsPerformance.csv"

print(" Experiment 1 ")
list_data = [10, 20, 30, 40, 50]
arr1 = np.array(list_data)
print(arr1)
print(arr1.shape)
print(arr1.dtype)

print("\n Experiment 2 ")
zeros_mat = np.zeros((3, 4))
ones_mat = np.ones((2, 5))
print(zeros_mat)
print(zeros_mat.shape)
print(ones_mat)
print(ones_mat.shape)

print("\n Experiment 3 ")
arr_1_to_12 = np.arange(1, 13)
reshaped_arr = arr_1_to_12.reshape(3, 4)
print(arr_1_to_12)
print(arr_1_to_12.shape)
print(reshaped_arr)
print(reshaped_arr.shape)

print("\n Experiment 4 ")
rand_arr = np.random.randint(1, 100, 10)
print(rand_arr)
print(rand_arr.min())
print(rand_arr.max())
print(rand_arr.mean())
print(rand_arr.sum())

print("\n Experiment 5 ")
data_dict = {'Name': ['Alice', 'Bob', 'Charlie'], 'Marks': [85, 90, 78]}
df_students = pd.DataFrame(data_dict)
print(df_students)
print(df_students.dtypes)

print("\n Experiment 6 ")
df_csv = pd.read_csv(url)
print(df_csv.head())
print(df_csv.tail())

print("\n Experiment 7 ")
df_csv.info()

print("\n Experiment 8 ")
summary = df_csv.describe()
print(summary)
print("\nMean:\n", summary.loc['mean'])
print("\nStandard Deviation:\n", summary.loc['std'])
print("\nMinimum:\n", summary.loc['min'])
print("\nMaximum:\n", summary.loc['max'])

--- Experiment 1 ---
[10 20 30 40 50]
(5,)
int64

--- Experiment 2 ---
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(3, 4)
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
(2, 5)

--- Experiment 3 ---
[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)

--- Experiment 4 ---
[62 99 42 96  3 72 51 12 85 33]
3
99
55.5
555

--- Experiment 5 ---
      Name  Marks
0    Alice     85
1      Bob     90
2  Charlie     78
Name     object
Marks     int64
dtype: object

--- Experiment 6 ---
   gender race/ethnicity parental level of education         lunch  \
0  female        group B           bachelor's degree      standard   
1  female        group C                some college      standard   
2  female        group B             master's degree      standard   
3    male        group A          associate's degree  free/reduced   
4    male        group C                some college      standard   

  test preparation course  math score  reading score  writing 